#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Read the file
with open('live/src/pages/terko-tipusok.astro', 'r', encoding='utf-8') as f:
    content = f.read()

# Final comprehensive fixes for remaining issues
final_fixes = {
    # Fix the title issues
    'Térkés': 'Térkő',
    'térkés': 'térkő',
    'Megfelelés': 'Megfelelő',
    'megfelelés': 'megfelelő',
    'mináségű': 'minőségű',
    'Mináségű': 'Minőségű',
    'mináség': 'minőség',
    'Mináság': 'Minőség',

    # Fix color and type names
    'Kávet': 'Kővet',
    'kávet': 'kővet',
    'Kávek': 'Kövek',
    'kávek': 'kövek',
    'Kés': 'Kő',
    'kés': 'kő',
    'kávet?': 'kővet?',
    'kávek': 'kövek',
    'Szánes': 'Színes',
    'szánes': 'színes',
    'szánek': 'színek',
    'Szánek': 'Színek',
    'szán': 'szín',
    'Szán': 'Szín',
    'szánpaletta': 'színpaletta',
    'Szánpaletta': 'Színpaletta',

    # Fix accent issues
    'elányei': 'előnyei',
    'Elányei': 'Előnyei',
    'Elányák': 'Előnyök',
    'elányák': 'előnyök',
    'ás': 'és',
    'Ás': 'És',
    'árokat': 'árakat',
    'Árokat': 'Árakat',
    'lehetáségeket': 'lehetőségeket',
    'Lehetáségeket': 'Lehetőségeket',
    'lehetáságek': 'lehetőségek',
    'Lehetáságek': 'Lehetőségek',
    'lehetáság': 'lehetőség',
    'Lehetáság': 'Lehetőség',
    'kÉvek': 'kövek',
    'KÉvek': 'Kövek',
    'tulajdonsága': 'tulajdonsága',
    'Tulajdonsága': 'Tulajdonsága',

    # Architecture/building terms
    'ápátászeti': 'építészeti',
    'Ápátászeti': 'Építészeti',
    'Építészete': 'építészete',
    'építészete': 'építészete',
    'jÉvő': 'jövő',
    'JÉvő': 'Jövő',
    'jÉvés': 'jövő',
    'JÉvés': 'Jövő',
    'idÉben': 'időben',
    'IdÉben': 'Időben',
    'IdÉvel': 'Idővel',
    'idÉvel': 'idővel',

    # Size and measurement terms
    'nagymáretű': 'nagyméretű',
    'Nagymáretű': 'Nagyméretű',
    'nagymáretés': 'nagyméretű',
    'Nagymáretés': 'Nagyméretű',
    'máretű': 'méretű',
    'Máretű': 'Méretű',
    'máretek': 'méretek',
    'Máretek': 'Méretek',
    'máretek': 'méretek',
    'Máretek': 'Méretek',
    'máretés': 'méretű',
    'Máretés': 'Méretű',
    'biztosít': 'biztosít',
    'Biztosít': 'Biztosít',
    'biztosát': 'biztosít',
    'Biztosát': 'Biztosít',

    # Material and durability terms
    'eredetés': 'eredetű',
    'Eredetés': 'Eredetű',
    'tartés': 'tartó',
    'Tartés': 'Tartó',
    'befektetés': 'befektetés',
    'Befektetés': 'Befektetés',
    'befektetős': 'befektetés',
    'Befektetős': 'Befektetés',
    'terhelhetáség': 'terhelhetőség',
    'Terhelhetáség': 'Terhelhetőség',
    'idátálló': 'időtálló',
    'Idátálló': 'Időtálló',
    'keményság': 'keménység',
    'Keményság': 'Keménység',
    'szápság': 'szépség',
    'Szápság': 'Szépség',
    'szápságáket': 'szépségüket',
    'Szápságáket': 'Szépségüket',
    'szápságűket': 'szépségüket',
    'Szápságűket': 'Szépségüket',
    'szápől': 'szépül',
    'Szápől': 'Szépül',
    'áregszik': 'öregszik',
    'Áregszik': 'Öregszik',

    # Common word fixes
    'elegőns': 'elegáns',
    'Elegőns': 'Elegáns',
    'elegŐciával': 'elegenciával',
    'ElegŐciával': 'Elegenciával',
    'elegáciával': 'elegenciával',
    'Elegáciával': 'Elegenciával',
    'mintázat': 'mintázat',
    'Mintázat': 'Mintázat',
    'mintőzat': 'mintázat',
    'Mintőzat': 'Mintázat',
    'mintőzatok': 'mintázatok',
    'Mintőzatok': 'Mintázatok',
    'kombinőciók': 'kombinációk',
    'Kombinőciók': 'Kombinációk',
    'kombinációk': 'kombinációk',
    'Kombinációk': 'Kombinációk',
    'kialakátásához': 'kialakításához',
    'Kialakátásához': 'Kialakításához',
    'textárák': 'textúrák',
    'Textárák': 'Textúrák',
    'kollekciő': 'kollekció',
    'Kollekciő': 'Kollekció',
    'kollekciés': 'kollekció',
    'Kollekciés': 'Kollekció',

    # Activity and place terms
    'játszátár': 'játszótér',
    'Játszátár': 'Játszótér',
    'dászátás': 'díszítés',
    'Dászátás': 'Díszítés',
    'dekoratív': 'dekoratív',
    'DekoratÉv': 'Dekoratív',
    'reprezentatív': 'reprezentatív',
    'ReprezentatÉv': 'Reprezentatív',
    'kreatív': 'kreatív',
    'Kreatív': 'Kreatív',
    'KreatÉv': 'Kreatív',
    'kreatÉv': 'kreatív',
    'KreatÉv': 'Kreatív',
    'Lakáterületek': 'Lakóterületek',
    'lakáterületek': 'lakóterületek',
    'medencákárnyezet': 'medencekörnyezet',
    'Medencákárnyezet': 'Medencekörnyezet',

    # Building and construction terms
    'telepátás': 'telepítés',
    'Telepátás': 'Telepítés',
    'telepőtős': 'telepítés',
    'Telepőtős': 'Telepítés',
    'átlagár': 'átlagár',
    'Átlagár': 'Átlagár',
    'alapvetés': 'alapvető',
    'Alapvetés': 'Alapvető',
    'sátátszürke': 'sötétszürke',
    'Sátátszürke': 'Sötétszürke',
    'járáfelületek': 'járófelületek',
    'Járáfelületek': 'Járófelületek',
    'járőfelületekhez': 'járófelületekhez',
    'Járőfelületekhez': 'Járófelületekhez',
    'járőfelületek': 'járófelületek',
    'Járőfelületek': 'Járófelületek',

    # Quality and project terms
    'mináságű': 'minőségű',
    'Mináságű': 'Minőségű',
    'mináságés': 'minőségű',
    'Mináságés': 'Minőségű',
    'csácsmináságű': 'csúcsminőségű',
    'Csácsmináságű': 'Csúcsminőségű',
    'térkávezési': 'térkövezési',
    'Térkávezési': 'Térkövezési',
    'tökéletes': 'tökéletes',
    'Tökéletes': 'Tökéletes',
    'kiválasztani': 'kiválasztani',
    'Kiválasztani': 'Kiválasztani',
    'kivőlasztani': 'kiválasztani',
    'Kivőlasztani': 'Kiválasztani',
    'térkávet': 'térkővet',
    'Térkávet': 'Térkővet',

    # Technical terms
    'vázelevezetés': 'vízelevezetés',
    'Vázelevezetés': 'Vízelevezetés',
    'vízelevezetést': 'vízelevezetést',
    'Vízelevezetést': 'Vízelevezetést',
    'vízelevezetésárt': 'vízelevezetésért',
    'Vízelevezetésárt': 'Vízelevezetésért',
    'vízáteresztő': 'vízáteresztő',
    'Vízáteresztő': 'Vízáteresztő',
    'vízáteresztés': 'vízáteresztő',
    'Vízáteresztés': 'Vízáteresztő',
    'teherviselés': 'teherhordó',
    'Teherviselés': 'Teherhordó',

    # Process and care terms
    'karbantartós': 'karbantartás',
    'Karbantartós': 'Karbantartás',
    'karbantartást': 'karbantartást',
    'Karbantartást': 'Karbantartást',
    'karbantartóssal': 'karbantartással',
    'Karbantartóssal': 'Karbantartással',
    'jelentásen': 'jelentősen',
    'Jelentásen': 'Jelentősen',
    'meghosszabbáthatja': 'meghosszabbíthatja',
    'Meghosszabbáthatja': 'Meghosszabbíthatja',
    'élettartamát': 'élettartamát',
    'Élettartamát': 'Élettartamát',
    'megárizheti': 'megőrizheti',
    'Megárizheti': 'Megőrizheti',

    # Simple character fixes
    'különbázé': 'különböző',
    'Különbázé': 'Különböző',
    'kőlánbázés': 'különböző',
    'Kőlánbázés': 'Különböző',
    'szőles': 'széles',
    'Szőles': 'Széles',
    'idájárásálló': 'időjárásálló',
    'Idájárásálló': 'Időjárásálló',
    'idájárásállóság': 'időjárásállóság',
    'Idájárásállóság': 'Időjárásállóság',
    'szakértés': 'szakértő',
    'Szakértés': 'Szakértő',
    'tanácsadással': 'tanácsadással',
    'Tanácsadással': 'Tanácsadással',
    'konzultáció': 'konzultáció',
    'Konzultáció': 'Konzultáció',
    'felmérés': 'felmérés',
    'Felmérés': 'Felmérés',
    'helyszíni': 'helyszíni',
    'Helyszíni': 'Helyszíni',

    # Maintenance action terms
    'használjon': 'használjon',
    'Használjon': 'Használjon',
    'hasznőljon': 'használjon',
    'Hasznőljon': 'Használjon',
    'tisztítószert': 'tisztítószert',
    'Tisztítószert': 'Tisztítószert',
    'tisztítászert': 'tisztítószert',
    'Tisztítászert': 'Tisztítószert',
    'távolítsa': 'távolítsa',
    'Távolítsa': 'Távolítsa',
    'TÉvolátsa': 'Távolítsa',
    'sörtéjű': 'sörtéjű',
    'Sörtéjű': 'Sörtéjű',
    'sártájés': 'sörtéjű',
    'Sártájés': 'Sörtéjű',
    'kefét': 'kefét',
    'Kefét': 'Kefét',
    'kefát': 'kefét',
    'Kefát': 'Kefét',
    'ellenőrizze': 'ellenőrizze',
    'Ellenőrizze': 'Ellenőrizze',
    'ellenárizze': 'ellenőrizze',
    'Ellenárizze': 'Ellenőrizze',
    'fugákat': 'fugákat',
    'Fugákat': 'Fugákat',
    'impregnálószert': 'impregnálószert',
    'Impregnálószert': 'Impregnálószert',
    'impregnőlászert': 'impregnálószert',
    'Impregnőlászert': 'Impregnálószert',
    'biztosítsa': 'biztosítsa',
    'Biztosítsa': 'Biztosítsa',
    'biztosátsa': 'biztosítsa',
    'Biztosátsa': 'Biztosítsa',
    'magasnyomásű': 'magasnyomású',
    'Magasnyomásű': 'Magasnyomású',
    'magasnyomásés': 'magasnyomású',
    'Magasnyomásés': 'Magasnyomású',
    'mosót': 'mosót',
    'Mosót': 'Mosót',
    'mosát': 'mosót',
    'Mosát': 'Mosót',
    'közelből': 'közelből',
    'Közelből': 'Közelből',
    'kázelből': 'közelből',
    'Kázelből': 'Közelből',
    'megszáradni': 'megszáradni',
    'Megszáradni': 'Megszáradni',
    'fémörtéjű': 'fémsörtéjű',
    'Fémörtéjű': 'Fémsörtéjű',
    'fámsártájés': 'fémsörtéjű',
    'Fámsártájés': 'Fémsörtéjű',
    'figyelmen': 'figyelmen',
    'Figyelmen': 'Figyelmen',
    'kívül': 'kívül',
    'Kívül': 'Kívül',
    'kÉvől': 'kívül',
    'KÉvől': 'Kívül',
    'repedéseket': 'repedéseket',
    'Repedéseket': 'Repedéseket',
    'repedáseket': 'repedéseket',
    'Repedáseket': 'Repedéseket',
    'sót': 'sót',
    'Sót': 'Sót',
    'sát': 'sót',
    'Sát': 'Sót',
    'idáben': 'időben',
    'Idáben': 'Időben',

    # Fix remaining special characters and combinations
    'ő40': 'x40',
    'ő30': 'x30',
    'ő ': '• ',
    '?': '✓',  # For list items
    'ŐciÉval': 'enciával',
    'RendkÉvüli': 'Rendkívüli',
    'rendkÉvüli': 'rendkívüli',
    'trejészetes': 'természetes',
    'Trejészetes': 'Természetes',
    'Természetes': 'Természetes',
    'természetes': 'természetes',
    'kövek': 'kövek',
    'Kövek': 'Kövek',
    'kővet': 'kővet',
    'Kővet': 'Kővet',
    'Összhasonlítása': 'Összehasonlítása',
    'összehasonlítása': 'összehasonlítása',

    # Common spelling errors
    'járda/át': 'járda/út',
    'Járda/át': 'Járda/út',
    'állóság': 'állóság',
    'Állóság': 'Állóság',
    'ütésálló': 'ütésálló',
    'Ütésálló': 'Ütésálló',
    'kopásállóság': 'kopásállóság',
    'Kopásállóság': 'Kopásállóság',
    'csúszásmentesség': 'csúszásmentesség',
    'Csúszásmentesség': 'Csúszásmentesség',

    # Specific text fixes for JavaScript content
    'adatbázis': 'adatbázis',
    'Adatbázis': 'Adatbázis',
    'ajánlások': 'ajánlások',
    'Ajánlások': 'Ajánlások',
    'felületű': 'felületű',
    'Felületű': 'Felületű',
    'optimalizálva': 'optimalizálva',
    'Optimalizálva': 'Optimalizálva',
    'elegancia': 'elegancia',
    'Elegancia': 'Elegancia',
    'élettartam': 'élettartam',
    'Élettartam': 'Élettartam',
    'maximális': 'maximális',
    'Maximális': 'Maximális',
    'keménység': 'keménység',
    'Keménység': 'Keménység',
    'értéknövelő': 'értéknövelő',
    'Értéknövelő': 'Értéknövelő',
    'garancia': 'garancia',
    'Garancia': 'Garancia',
    'mintázat': 'mintázat',
    'Mintázat': 'Mintázat',
    'szépül': 'szépül',
    'Szépül': 'Szépül',
    'textúrák': 'textúrák',
    'Textúrák': 'Textúrák',
    'exkluzív': 'exkluzív',
    'Exkluzív': 'Exkluzív',
    'kollekció': 'kollekció',
    'Kollekció': 'Kollekció',
    'pigmentek': 'pigmentek',
    'Pigmentek': 'Pigmentek',
    'környezetbarát': 'környezetbarát',
    'Környezetbarát': 'Környezetbarát',
    'történelmi': 'történelmi',
    'Történelmi': 'Történelmi',
    'reprezentatív': 'reprezentatív',
    'Reprezentatív': 'Reprezentatív',
    'befektetés': 'befektetés',
    'Befektetés': 'Befektetés',
    'csúcsminőségű': 'csúcsminőségű',
    'Csúcsminőségű': 'Csúcsminőségű',
    'központokhoz': 'központokhoz',
    'Központokhoz': 'Központokhoz',
    'generálása': 'generálása',
    'Generálása': 'Generálása',
    'ajánláshoz': 'ajánláshoz',
    'Ajánláshoz': 'Ajánláshoz',
    'egyezés': 'egyezés',
    'Egyezés': 'Egyezés',
    'alapértelmezett': 'alapértelmezett',
    'Alapértelmezett': 'Alapértelmezett',
    'használat': 'használat',
    'Használat': 'Használat',
    'alapján': 'alapján',
    'Alapján': 'Alapján',
    'ajánlás': 'ajánlás',
    'Ajánlás': 'Ajánlás',
    'megjelenítése': 'megjelenítése',
    'Megjelenítése': 'Megjelenítése',

    # Fix specific phrases found in HTML
    'előnyők': 'előnyök',
    'Előnyők': 'Előnyök',
    'Jellemzák': 'Jellemzők',
    'jellemzák': 'jellemzők',
    'szánpaletta': 'színpaletta',
    'Szánpaletta': 'Színpaletta',
    'övezetek': 'övezetek',
    'Övezetek': 'Övezetek',
    'övezetek': 'övezetek',
    'Övezetek': 'Övezetek',
    'Évezetek': 'Övezetek',
    'évezetek': 'övezetek',
    'designlehetáságek': 'designlehetőségek',
    'Designlehetáságek': 'Designlehetőségek',
    'pigmentezás': 'pigmentezés',
    'Pigmentezás': 'Pigmentezés',
    'felületkezelásek': 'felületkezelések',
    'Felületkezelásek': 'Felületkezelések',

    # Icon fixes that were causing issues
    'elányák': 'előnyök',
    'Elányák': 'Előnyök',
    'ár-árták': 'ár-érték',
    'Ár-árták': 'Ár-érték',
    'kedvezés': 'kedvező',
    'Kedvezés': 'Kedvező',

    # Question mark and special character issues
    'térkövek?': 'térkövek?',
    'Figyeljen?': 'Figyeljen?',
    'célja?': 'célja?',
    'költségvetés?': 'költségvetés?',
    'vállal?': 'vállal?',
    'Megfelelő?': 'Megfelelő?',

    # Fix icons that got corrupted with star symbols
    '⭐⭐⭐⭐?': '⭐⭐⭐⭐⭐',
    '💰?': '⭐⭐⭐',
    '⭐⭐⭐⭐': '⭐⭐⭐⭐',
    '💰': '⭐⭐⭐',

    # Final check for remaining encoding issues
    'hászigetelő': 'hőszigetelő',
    'Hászigetelő': 'Hőszigetelő',
    'jás': 'jó',
    'Jás': 'Jó',
    'kitűnés': 'kitűnő',
    'Kitűnés': 'Kitűnő',
    'tónusok': 'tónusok',
    'Tónusok': 'Tónusok',
    'tánusok': 'tónusok',
    'Tánusok': 'Tónusok',
    'patinát': 'patinát',
    'Patinát': 'Patinát',
    'forgalmé': 'forgalmú',
    'Forgalmé': 'Forgalmú',
    'forgalmés': 'forgalmú',
    'Forgalmés': 'Forgalmú',
}

# Apply all the fixes
for old, new in final_fixes.items():
    content = content.replace(old, new)

# Specific contextual replacements to fix icon issues
content = content.replace('🔧 Szakértői Karbantartási', '🔧 Szakértői Karbantartási')
content = content.replace('🎯 Térkő Választási', '🎯 Térkő Választási')
content = content.replace('🏗️ Használati Területek', '🏗️ Használati Területek')
content = content.replace('📊 Beton Térkő Típusok', '📊 Beton Térkő Típusok')
content = content.replace('📊 Természetes Kövek', '📊 Természetes Kövek')
content = content.replace('📊 Komplett Költségkalkuláció', '📊 Komplett Költségkalkuláció')
content = content.replace('🧽 Térkő Karbantartási', '🧽 Térkő Karbantartási')

# Fix list bullets to be consistent
content = content.replace('<li>és ', '<li>• ')
content = content.replace('<li>✓ ', '<li>• ')

# Write the final corrected content back
with open('live/src/pages/terko-tipusok.astro', 'w', encoding='utf-8') as f:
    f.write(content)

print("Final character encoding cleanup completed!")
print("All Hungarian text should now be properly encoded and readable.")